### ISSUE TITLE
feat: Support more languages!

### ISSUE THREAD

**Issue by pawamoy** [davep/textual-astview#13]
Hey @davep, I'm once again opening a feature request with zero urgency :smile: 

I'm starting to work on adding support for other languages than Python in mkdocstrings. And it came to my mind that having a tool like `astare` for other languages would be extremely helpful. So I thought, why not `astare` itself?

[tree-sitter](https://pypi.org/project/tree-sitter/) provides parsers for almost every language (that's what I'll be using), so maybe it could be used in this project? I'll try to give more details once I'm accustomed to it :slightly_smiling_face: 

Also, feel free to close this as "not in scope"!

**Comment by davep** [comment]
Nice idea, but I sense that would be better done as a dedicated TS explorer app, really. This app is deliberately simple and relatively standalone; as we've seen from Textual's text editing code: tree sitter support is quite the dependency overhead. 

I honestly think it would be better as a brand new application. 

Just not with me as the author. 😉

**Comment by pawamoy** [comment]
Haha, fair enough :slightly_smiling_face: I will close this then, and keep the idea in mind. Thanks for your feedback!
